name: Deploy CloudFormation

on:
  push:
    branches:
        - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: aws-actions/aws-cloudformation-github-deploy@v1

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy CloudFormation
      run: |
        aws cloudformation create-stack \
          --stack-name MyStack \
  --template-file <filename>
